export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORYS_REJECTED';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORY_FULFILLED = 'FETCH_CATEGORY_FULFILLED';
export const FETCH_CATEGORY_REJECTED = 'FETCH_CATEGORY_REJECTED';
